[package]
name = "obfany"
version = "0.1.4"
edition = "2024"
rust-version = "1.85"
license = "MIT"
description = "Compiletime string, number, and boolean constant obfuscation for Rust"
authors = ["jeanzuck"]
documentation = "https://docs.rs/obfany"
repository = "https://github.com/jeanzuck/obfany"
readme = "README.md"
keywords = ["obfuscation", "reverse-engineering", "static-analysis", "no-std"]
categories = ["no-std"]
