[package]
name = "obfany"
version = "0.1.0"
edition = "2021"
license = "MIT"

authors = ["jeanzuck"]
description = "Compiletime string and number constant obfuscation for Rust"
documentation = "https://docs.rs/obfany"
repository = "https://github.com/jeanzuck/obfany"
readme = "readme.md"
keywords = ["obfuscation", "string", "number", "random", "no-std"]
categories = ["no-std"]
